# Summary

*   This file loads and merges two xlsx spreadsheets, which include oil vessel arrival data into Portland for 2020 and 2021.
*   Key columns are: Arrival date, Terminal (for final delivery), Product Type, Product Amount (Incoming and Outgoing)
*   Possible key columns with empty or mostly empty data: Arrival time.
*   Separate columns were added for Year/Month/Day

# For updating after our project ends:
User uploading data from Excel should do the following first (in Excel):

1.   delete empty rows above column names;
2.   delete unneeded sheets;
3.   save as csv.

# Tidying next steps: 
*   Change data type of Arrival Time values to DateTime, so that this notebook can correctly load Arrival Time values in the future?
*   Should this notebook produce the final, tidied dataframe in a way that can be accessed from a different notebook?

In [56]:
import pandas as pd

url_2020 = 'https://raw.githubusercontent.com/ds5110/stinky/master/2020%20SMRO%20VESSEL%20ARRIVALS.csv'
url_2021 = 'https://raw.githubusercontent.com/ds5110/stinky/master/2021%20SMRO%20VESSEL%20ARRIVALS.csv'

df_2020 = pd.read_csv(url_2020)
df_2021 = pd.read_csv(url_2021)

In [57]:
df_2020.head()

  2020 VESSEL ARRIVALS SMRO  ... Unnamed: 13
0                       NaN  ...         NaN
1                       NaN  ...         NaN
2             ARRIVAL\nDATE  ...         NaN
3                       NaN  ...         NaN
4                    1/2/20  ...         NaN

[5 rows x 14 columns]

In [58]:
df_2021.head()

  2021 VESSEL ARRIVALS SMRO  ... Unnamed: 13
0                       NaN  ...         NaN
1                       NaN  ...         NaN
2             ARRIVAL\nDATE  ...         NaN
3                       NaN  ...         NaN
4                    1/4/21  ...         NaN

[5 rows x 14 columns]

In [59]:
# drop last column
df_2020.drop(df_2020.columns[-1], axis=1, inplace=True)

# set correct column name
df_2020.columns = df_2020.iloc[2]

# drop empty rows
df_2020.drop(labels=[0, 1, 2, 3], axis=0, inplace=True)

# rename columns
df_2020.columns = ['ARRIVAL DATE', 'ARRIVAL TIME (if avail)', 'TERMINAL', 'SHIP NAME', 'LAST PORT OF CALL (if avail)', 'PRODUCT TYPE - OIL', 'PRODUCT AMOUNT - OIL, Incoming (Multiply metric tons by 7.5 for approx bbls)', 'PRODUCT AMOUNT - OIL, Outgoing', 'RUNNING TOTAL', 'PRODUCT TYPE - NON-OIL',	'PRODUCT AMOUNT - NON OIL, Incoming', 'PRODUCT AMOUNT - NON OIL, Outgoing', 'Running Total (Specify units)']

# drop rows in which Arrival Time is NaN
df_2020.drop(df_2020.loc[pd.isna(df_2020['ARRIVAL DATE'])].index, axis=0, inplace=True)

df_2020

    ARRIVAL DATE  ... Running Total (Specify units)
4         1/2/20  ...                             0
5         1/2/20  ...                             0
6         1/2/20  ...                             0
7         1/2/20  ...                             0
8         1/2/20  ...                             0
..           ...  ...                           ...
559      12/4/20  ...                             0
560     12/23/20  ...                             0
561      12/9/20  ...                             0
562     12/14/20  ...                             0
563     12/14/20  ...                             0

[560 rows x 13 columns]

In [60]:
# Creating separate year/month/day columns
df_2020['ARRIVAL DATE']=pd.to_datetime(df_2020['ARRIVAL DATE'])
df_2020['Year']=df_2020['ARRIVAL DATE'].dt.year
df_2020['Month']=df_2020['ARRIVAL DATE'].dt.month
df_2020['Day']=df_2020['ARRIVAL DATE'].dt.day
df_2020

    ARRIVAL DATE ARRIVAL TIME (if avail) TERMINAL  ...  Year Month Day
4     2020-01-02                     NaN    Citgo  ...  2020     1   2
5     2020-01-02                     NaN    Citgo  ...  2020     1   2
6     2020-01-02                     NaN    Citgo  ...  2020     1   2
7     2020-01-02                     NaN    Citgo  ...  2020     1   2
8     2020-01-02                     NaN    Citgo  ...  2020     1   2
..           ...                     ...      ...  ...   ...   ...  ..
559   2020-12-04                     NaN  Global   ...  2020    12   4
560   2020-12-23                     NaN  Global   ...  2020    12  23
561   2020-12-09                     NaN  Sprague  ...  2020    12   9
562   2020-12-14                     NaN  Sprague  ...  2020    12  14
563   2020-12-14                     NaN  Sprague  ...  2020    12  14

[560 rows x 16 columns]

In [61]:
# drop last column
df_2021.drop(df_2021.columns[-1], axis=1, inplace=True)

# set correct column name
df_2021.columns = df_2021.iloc[2]

# drop empty rows
df_2021.drop(labels=[0, 1, 2, 3], axis=0, inplace=True)

# rename columns
df_2021.columns = ['ARRIVAL DATE', 'ARRIVAL TIME (if avail)', 'TERMINAL', \
                   'SHIP NAME', 'LAST PORT OF CALL (if avail)', \
                   'PRODUCT TYPE - OIL', 'PRODUCT AMOUNT - OIL, Incoming (Multiply metric tons by 7.5 for approx bbls)', \
                   'PRODUCT AMOUNT - OIL, Outgoing', 'RUNNING TOTAL', \
                   'PRODUCT TYPE - NON-OIL',	\
                   'PRODUCT AMOUNT - NON OIL, Incoming', \
                   'PRODUCT AMOUNT - NON OIL, Outgoing', 'Running Total (Specify units)']

# drop rows in which Arrival Time is NaN
df_2021.drop(df_2021.loc[pd.isna(df_2021['ARRIVAL DATE'])].index, axis=0, inplace=True)

df_2021

    ARRIVAL DATE  ... Running Total (Specify units)
4         1/4/21  ...                             0
5         1/4/21  ...                             0
6         1/4/21  ...                             0
7        1/10/21  ...                             0
8         1/7/21  ...                             0
..           ...  ...                           ...
209      5/30/21  ...                             0
210       5/4/21  ...                             0
211       5/4/21  ...                             0
212      5/21/21  ...                             0
213      5/20/21  ...                             0

[210 rows x 13 columns]

In [62]:
# Correcting an error in a date to actual date format
df_2021["ARRIVAL DATE"].replace({"2/13/20221": "2/13/2021"}, inplace=True)

# Creating separate year/month/day columns
df_2021['ARRIVAL DATE']=pd.to_datetime(df_2021['ARRIVAL DATE'])
df_2021['Year']=df_2021['ARRIVAL DATE'].dt.year
df_2021['Month']=df_2021['ARRIVAL DATE'].dt.month
df_2021['Day']=df_2021['ARRIVAL DATE'].dt.day
df_2021

    ARRIVAL DATE ARRIVAL TIME (if avail)           TERMINAL  ...  Year Month Day
4     2021-01-04                     NaN              Citgo  ...  2021     1   4
5     2021-01-04                     NaN              Citgo  ...  2021     1   4
6     2021-01-04                     NaN              Citgo  ...  2021     1   4
7     2021-01-10                     NaN              Citgo  ...  2021     1  10
8     2021-01-07                     NaN              Citgo  ...  2021     1   7
..           ...                     ...                ...  ...   ...   ...  ..
209   2021-05-30                     NaN             Global  ...  2021     5  30
210   2021-05-04                     NaN            Sprague  ...  2021     5   4
211   2021-05-04                     NaN            Sprague  ...  2021     5   4
212   2021-05-21                     NaN  Portland Pipeline  ...  2021     5  21
213   2021-05-20                     NaN  Portland Pipeline  ...  2021     5  20

[210 rows x 16 columns]

In [63]:
# Merge two df
df_vessels = df_2020.append(df_2021, ignore_index=True)
df_vessels

    ARRIVAL DATE ARRIVAL TIME (if avail)           TERMINAL  ...  Year Month Day
0     2020-01-02                     NaN              Citgo  ...  2020     1   2
1     2020-01-02                     NaN              Citgo  ...  2020     1   2
2     2020-01-02                     NaN              Citgo  ...  2020     1   2
3     2020-01-02                     NaN              Citgo  ...  2020     1   2
4     2020-01-02                     NaN              Citgo  ...  2020     1   2
..           ...                     ...                ...  ...   ...   ...  ..
765   2021-05-30                     NaN             Global  ...  2021     5  30
766   2021-05-04                     NaN            Sprague  ...  2021     5   4
767   2021-05-04                     NaN            Sprague  ...  2021     5   4
768   2021-05-21                     NaN  Portland Pipeline  ...  2021     5  21
769   2021-05-20                     NaN  Portland Pipeline  ...  2021     5  20

[770 rows x 16 columns]

In [64]:
# Sorting the dates chronologically after merging the datasets
df_vessels=df_vessels.sort_values(by='ARRIVAL DATE')

# Resetting index
df_vessels=df_vessels.reset_index(drop=True)

In [65]:
df_vessels

    ARRIVAL DATE ARRIVAL TIME (if avail) TERMINAL  ...  Year Month Day
0     2020-01-02                     NaN    Citgo  ...  2020     1   2
1     2020-01-02                     NaN    Citgo  ...  2020     1   2
2     2020-01-02                     NaN    Citgo  ...  2020     1   2
3     2020-01-02                     NaN    Citgo  ...  2020     1   2
4     2020-01-02                     NaN    Citgo  ...  2020     1   2
..           ...                     ...      ...  ...   ...   ...  ..
765   2021-05-29                     NaN   Global  ...  2021     5  29
766   2021-05-29                     NaN   Global  ...  2021     5  29
767   2021-05-30                     NaN   Global  ...  2021     5  30
768   2021-05-30                     NaN   Global  ...  2021     5  30
769   2021-05-30                     NaN     Gulf  ...  2021     5  30

[770 rows x 16 columns]

In [66]:
# find out type of Product Amount column values - includes float values
print([type(x) for x in df_vessels['PRODUCT AMOUNT - OIL, Incoming (Multiply metric tons by 7.5 for approx bbls)']])

[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'float'>, <class 'float'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'float'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'float'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'float'>, <class 'str'>, <class 'float'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'float'>, <class 'float'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'float'>, <class 'float'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]

In [67]:
# convert Product Amount columns and last column to float
df_vessels['PRODUCT AMOUNT - OIL, Incoming (Multiply metric tons by 7.5 for approx bbls)']\
 = [float(str(x).replace(',', '')) for x in df_vessels['PRODUCT AMOUNT - OIL, Incoming (Multiply metric tons by 7.5 for approx bbls)']]
df_vessels['PRODUCT AMOUNT - OIL, Outgoing'] = [float(str(x).replace(',', '')) for x in df_vessels['PRODUCT AMOUNT - OIL, Outgoing']]
df_vessels['Running Total (Specify units)'] = [float(str(x).replace(',', '')) for x in df_vessels['PRODUCT AMOUNT - OIL, Outgoing']]
df_vessels

    ARRIVAL DATE ARRIVAL TIME (if avail) TERMINAL  ...  Year Month Day
0     2020-01-02                     NaN    Citgo  ...  2020     1   2
1     2020-01-02                     NaN    Citgo  ...  2020     1   2
2     2020-01-02                     NaN    Citgo  ...  2020     1   2
3     2020-01-02                     NaN    Citgo  ...  2020     1   2
4     2020-01-02                     NaN    Citgo  ...  2020     1   2
..           ...                     ...      ...  ...   ...   ...  ..
765   2021-05-29                     NaN   Global  ...  2021     5  29
766   2021-05-29                     NaN   Global  ...  2021     5  29
767   2021-05-30                     NaN   Global  ...  2021     5  30
768   2021-05-30                     NaN   Global  ...  2021     5  30
769   2021-05-30                     NaN     Gulf  ...  2021     5  30

[770 rows x 16 columns]

In [68]:
# replace NaN in Product Amount - Oil, Incoming and Outgoing with 0
df_vessels['PRODUCT AMOUNT - OIL, Outgoing'].fillna(0, inplace=True)
df_vessels['PRODUCT AMOUNT - OIL, Incoming (Multiply metric tons by 7.5 for approx bbls)'].fillna(0, inplace=True)
df_vessels

    ARRIVAL DATE ARRIVAL TIME (if avail) TERMINAL  ...  Year Month Day
0     2020-01-02                     NaN    Citgo  ...  2020     1   2
1     2020-01-02                     NaN    Citgo  ...  2020     1   2
2     2020-01-02                     NaN    Citgo  ...  2020     1   2
3     2020-01-02                     NaN    Citgo  ...  2020     1   2
4     2020-01-02                     NaN    Citgo  ...  2020     1   2
..           ...                     ...      ...  ...   ...   ...  ..
765   2021-05-29                     NaN   Global  ...  2021     5  29
766   2021-05-29                     NaN   Global  ...  2021     5  29
767   2021-05-30                     NaN   Global  ...  2021     5  30
768   2021-05-30                     NaN   Global  ...  2021     5  30
769   2021-05-30                     NaN     Gulf  ...  2021     5  30

[770 rows x 16 columns]

In [69]:
# Recalculate Running Total values (errors in xlsx files and to reflect merged df's)
running_total = []
net = df_vessels['PRODUCT AMOUNT - OIL, Incoming (Multiply metric tons by 7.5 for approx bbls)'][0]
running_total.append(net)
for i in range(1, len(df_vessels)):
  net += df_vessels['PRODUCT AMOUNT - OIL, Incoming (Multiply metric tons by 7.5 for approx bbls)'][i]
  net -= df_vessels['PRODUCT AMOUNT - OIL, Outgoing'][i]
  running_total.append(net)
df_vessels['RUNNING TOTAL'] = running_total

df_vessels

    ARRIVAL DATE ARRIVAL TIME (if avail) TERMINAL  ...  Year Month Day
0     2020-01-02                     NaN    Citgo  ...  2020     1   2
1     2020-01-02                     NaN    Citgo  ...  2020     1   2
2     2020-01-02                     NaN    Citgo  ...  2020     1   2
3     2020-01-02                     NaN    Citgo  ...  2020     1   2
4     2020-01-02                     NaN    Citgo  ...  2020     1   2
..           ...                     ...      ...  ...   ...   ...  ..
765   2021-05-29                     NaN   Global  ...  2021     5  29
766   2021-05-29                     NaN   Global  ...  2021     5  29
767   2021-05-30                     NaN   Global  ...  2021     5  30
768   2021-05-30                     NaN   Global  ...  2021     5  30
769   2021-05-30                     NaN     Gulf  ...  2021     5  30

[770 rows x 16 columns]